version: "2.0"

services:
  znc:
    image: lscr.io/linuxserver/znc:latest
    container_name: znc
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - /path/to/data:/config
    ports:
      - 6501:6501
    restart: unless-stopped
    depends_on:
      - bitlbee
  bitlbee:
    build: .
    image: mbologna/docker-bitlbee
    container_name: bitlbee
    restart: unless-stopped
    ports:
      - "16667:6667"
    networks:
      - bitlbee
    volumes:
      - ./etc/bitlbee:/usr/local/etc/bitlbee
      - bitlbee_data:/var/lib/bitlbee

volumes:
  bitlbee_data:

networks:
  bitlbee:

